# -*- coding: utf-8 -*-
#
'''
Classe com a lista de comandos para plugins
Lista baseada no RFC2812
'''
class Comandos:
    ''' Códigos de resposta '''
    RPL_WELCOME           = '001' # "Welcome to the Internet Relay Network
    RPL_YOURHOST          = '002' # "Your host is <servername>, running version <ver>"'004',
    RPL_CREATED           = '003' # "This server was created <date>"
    RPL_MYINFO            = '004' # "<servername> <version> <available user modes> <available canal modes>"
    RPL_BOUNCE            = '005' # "Try server <server name>, port <port number>"
    RPL_USERHOST          = '302' # ":*1<reply> *( " " <reply> )
    RPL_ISON              = '303' # ":*1<nick> *( " " <nick> )"
    RPL_AWAY              = '301' # "<nick> :<away message>"
    RPL_UNAWAY            = '305' # ":You are no longer marked as being away"
    RPL_NOWAWAY           = '306' # ":You have been marked as being away"
    RPL_WHOISUSER         = '311' # "<nick> <user> <host> * :<real name>"
    RPL_WHOISSERVER       = '312' # "<nick> <server> :<server info>"
    RPL_WHOISOPERATOR     = '313' # "<nick> :is an IRC operator"
    RPL_WHOISIDLE         = '317' # "<nick> <integer> :seconds idle"
    RPL_ENDOFWHOIS        = '318' # "<nick> :End of WHOIS list"
    RPL_WHOISCHANNELS     = '319' # "<nick> :*( ( "@" / "+" ) <canal> " " )"
    RPL_WHOWASUSER        = '314' # "<nick> <user> <host> * :<real name>"
    RPL_ENDOFWHOWAS       = '369' # "<nick> :End of WHOWAS"
    RPL_LISTSTART         = '321' # Obsolete. Not used.
    RPL_LIST              = '322' # "<canal> <# visible> :<topic>"
    RPL_LISTEND           = '323' # ":End of LIST"
    RPL_UNIQOPIS          = '325' # "<canal> <nickname>"
    RPL_CHANNELMODEIS     = '324' # "<canal> <mode> <mode params>"
    RPL_NOTOPIC           = '331' # "<canal> :No topic is set"
    RPL_TOPIC             = '332' # "<canal> :<topic>"
    RPL_WHEN_TOPIC        = '333' # "<canal> <nick> 902508764
    RPL_INVITING          = '341' # "<canal> <nick>"
    RPL_SUMMONING         = '342' # "<user> :Summoning user to IRC"
    RPL_INVITELIST        = '346' # "<canal> <invitemask>"
    RPL_ENDOFINVITELIST   = '347' # "<canal> :End of canal invite list"
    RPL_EXCEPTLIST        = '348' # "<canal> <exceptionmask>"
    RPL_ENDOFEXCEPTLIST   = '349' # "<canal> :End of canal exception list"
    RPL_VERSION           = '351' # "<version>.<debuglevel> <server> :<comments>"
    RPL_WHOREPLY          = '352' # "<canal> <user> <host> <server> <nick>\r\n( "H" / "G" > ["*"] [ ( "@" / "+" ) ]\r\n:<hopcount> <real name>"
    RPL_ENDOFWHO          = '315' # "<name> :End of WHO list"
    RPL_NAMREPLY          = '353' # "( "=" / "*" / "@" ) <canal>\r\n:[ "@" / "+" ] <nick> *( " " [ "@" / "+" ] <nick> )"
    RPL_ENDOFNAMES        = '366' # "<canal> :End of NAMES list"
    RPL_LINKS             = '364' # "<mask> <server> :<hopcount> <server info>"
    RPL_ENDOFLINKS        = '365' # "<mask> :End of LINKS list"
    RPL_BANLIST           = '367' # "<canal> <banmask>"
    RPL_ENDOFBANLIST      = '368' # "<canal> :End of canal ban list"
    RPL_INFO              = '371' # ":<string>"
    RPL_ENDOFINFO         = '374' # ":End of INFO list"
    RPL_MOTDSTART         = '375' # ":- <server> Message of the day - "
    RPL_MOTD              = '372' # ":- <text>"
    RPL_ENDOFMOTD         = '376' # RPL_ENDOFMOTD
    RPL_YOUREOPER         = '381' # ":You are now an IRC operator"
    RPL_REHASHING         = '382' # "<config file> :Rehashing"
    RPL_YOURESERVICE      = '383' # "You are service <servicename>"
    RPL_TIME              = '391' # "<server> :<string showing servers local time>"
    RPL_USERSSTART        = '392' # ":UserID    Terminal Host"
    RPL_USERS             = '393' # ":<username> <ttyline> <hostname>"
    RPL_ENDOFUSERS        = '394' # ":End of users"
    RPL_NOUSERS           = '395' # ":Nobody logged in"
    RPL_TRACELINK         = '200' # "Link <version & debug level> <destination> <next server> V<protocol version> <link uptime in seconds> <backstream sendq> <upstream sendq>"
    RPL_TRACECONNECTING   = '201' # "Try. <class> <server>"
    RPL_TRACEHANDSHAKE    = '202' # "H.S. <class> <server>"
    RPL_TRACEUNKNOWN      = '203' # "???? <class> [<client IP address in dot form>]"
    RPL_TRACEOPERATOR     = '204' # "Oper <class> <nick>"
    RPL_TRACEUSER         = '205' # "User <class> <nick>"
    RPL_TRACESERVER       = '206' # "Serv <class> <int>S <int>C <server> <nick!user|*!*>@<host|server> V<protocol version>"
    RPL_TRACESERVICE      = '207' # "Service <class> <name> <type> <active type>"
    RPL_TRACENEWTYPE      = '208' # "<newtype> 0 <client name>"
    RPL_TRACECLASS        = '209' # "Class <class> <count>"
    RPL_TRACERECONNECT    = '210' # Unused.
    RPL_TRACELOG          = '261' # "File <logfile> <debug level>"
    RPL_TRACEEND          = '262' # "<server name> <version & debug level> :End of TRACE"
    RPL_STATSLINKINFO     = '211' # "<linkname> <sendq> <sent messages> <sent Kbytes> <received messages> <received Kbytes> <time open>"
    RPL_STATSCOMMANDS     = '212' # "<command> <count> <byte count> <remote count>"
    RPL_ENDOFSTATS        = '219' # "<stats letter> :End of STATS report"
    RPL_STATSUPTIME       = '242' # ":Server Up %d days %d:%02d:%02d"
    RPL_STATSOLINE        = '243' # "O <hostmask> * <name>"
    RPL_UMODEIS           = '221' # "<user mode string>"
    RPL_SERVLIST          = '234' # "<name> <server> <mask> <type> <hopcount> <info>"
    RPL_SERVLISTEND       = '235' # "<mask> <type> :End of service listing"
    RPL_LUSERCLIENT       = '251' # ":There are <integer> users and <integer> services on <integer> servers"
    RPL_LUSEROP           = '252' # "<integer> :operator(s) online"
    RPL_LUSERUNKNOWN      = '253' # "<integer> :unknown connection(s)"
    RPL_LUSERCHANNELS     = '254' # "<integer> :canals formed"
    RPL_LUSERME           = '255' # ":I have <integer> clients and <integer> servers"
    RPL_ADMINME           = '256' # "<server> :Administrative info"
    RPL_ADMINLOC1         = '257' # ":<admin info>"
    RPL_ADMINLOC2         = '258' # ":<admin info>"
    RPL_ADMINEMAIL        = '259' # ":<admin info>"
    RPL_TRYAGAIN          = '263' # "<command> :Please wait a while and try again."
    RPL_FORWARDING        = '470' # Redirecionando para outro canal
    ''' Códigos de erros '''
    ERR_NOSUCHNICK        = '401' # "<nickname> :No such nick/canal"
    ERR_NOSUCHSERVER      = '402' # "<server name> :No such server"
    ERR_NOSUCHCHANNEL     = '403' # "<canal name> :No such canal"
    ERR_CANNOTSENDTOCHAN  = '404' # "<canal name> :Cannot send to canal"
    ERR_TOOMANYCHANNELS   = '405' # "<canal name> :You have joined too many canals"
    ERR_WASNOSUCHNICK     = '406' # "<nickname> :There was no such nickname"
    ERR_TOOMANYTARGETS    = '407' # "<target> :<error code> recipients. <abort message>"
    ERR_NOSUCHSERVICE     = '408' # "<service name> :No such service"
    ERR_NOORIGIN          = '409' # ":No origin specified"
    ERR_NORECIPIENT       = '411' # ":No recipient given (<command>)"
    ERR_NOTEXTTOSEND      = '412' # ":No text to send"
    ERR_NOTOPLEVEL        = '413' # "<mask> :No toplevel domain specified"
    ERR_WILDTOPLEVEL      = '414' # "<mask> :Wildcard in toplevel domain"
    ERR_BADMASK           = '415' # "<mask> :Bad Server/host mask"
    ERR_UNKNOWNCOMMAND    = '421' # "<command> :Unknown command"
    ERR_NOMOTD            = '422' # ":MOTD File is missing"
    ERR_NOADMININFO       = '423' # "<server> :No administrative info available"
    ERR_FILEERROR         = '424' # ":File error doing <file op> on <file>"
    ERR_NONICKNAMEGIVEN   = '431' # ":No nickname given"
    ERR_ERRONEUSNICKNAME  = '432' # "<nick> :Erroneous nickname"
    ERR_NICKNAMEINUSE     = '433' # "<nick> :Nickname is already in use"
    ERR_NICKCOLLISION     = '436' # "<nick> :Nickname collision KILL from <user>@<host>"
    ERR_UNAVAILRESOURCE   = '437' # "<nick/canal> :Nick/canal is temporarily unavailable"
    ERR_USERNOTINCHANNEL  = '441' # "<nick> <canal> :They arent on that canal"
    ERR_NOTONCHANNEL      = '442' # "<canal> :Youre not on that canal"
    ERR_USERONCHANNEL     = '443' # "<user> <canal> :is already on canal"
    ERR_NOLOGIN           = '444' # "<user> :User not logged in"
    ERR_SUMMONDISABLED    = '445' # ":SUMMON has been disabled"
    ERR_USERSDISABLED     = '446' # ":USERS has been disabled"
    ERR_NOTREGISTERED     = '451' # ":You have not registered"
    ERR_NEEDMOREPARAMS    = '461' # "<command> :Not enough parameters"
    ERR_ALREADYREGISTRED  = '462' # ":Unauthorized command (already registered)"
    ERR_NOPERMFORHOST     = '463' # ":Your host isnt among the privileged"
    ERR_PASSWDMISMATCH    = '464' # ":Password incorrect"
    ERR_YOUREBANNEDCREEP  = '465' # ":You are banned from this server"
    ERR_YOUWILLBEBANNED   = '466' # Aviso que voce sera banido
    ERR_KEYSET            = '467' # "<canal> :Channel key already set"
    ERR_CHANNELISFULL     = '471' # "<canal> :Cannot join canal (+l)"
    ERR_UNKNOWNMODE       = '472' # "<char> :is unknown mode char to me for <canal>"
    ERR_INVITEONLYCHAN    = '473' # "<canal> :Cannot join canal (+i)"
    ERR_BANNEDFROMCHAN    = '474' # "<canal> :Cannot join canal (+b)"
    ERR_BADCHANNELKEY     = '475' # "<canal> :Cannot join canal (+k)"
    ERR_BADCHANMASK       = '476' # "<canal> :Bad Channel Mask"
    ERR_NOCHANMODES       = '477' # "<canal> :Channel doesnt support modes"
    ERR_BANLISTFULL       = '478' # "<canal> <char> :Channel list is full"
    ERR_NOPRIVILEGES      = '481' # ":Permission Denied- Youre not an IRC operator"
    ERR_CHANOPRIVSNEEDED  = '482' # "<canal> :Youre not canal operator"
    ERR_CANTKILLSERVER    = '483' # ":You cant kill a server!"
    ERR_RESTRICTED        = '484' # ":Your connection is restricted!"
    ERR_UNIQOPPRIVSNEEDED = '485' # ":Youre not the original canal operator"
    ERR_NOOPERHOST        = '491' # ":No O-lines for your host"
    ERR_UMODEUNKNOWNFLAG  = '501' # ":Unknown MODE flag"
    ERR_USERSDONTMATCH    = '502' # ":Cannot change mode for other users"
    ''' CTCP '''
    CTCP_VERSION  = '\x01VERSION\x01'
    CTCP_USERINFO = '\x01USERINFO\x01'
    ''' Outros comandos '''
    CMD_JOIN    = 'JOIN'
    CMD_MODE    = 'MODE'
    CMD_KICK    = 'KICK'
    CMD_PART    = 'PART'
    CMD_QUIT    = 'QUIT'
    CMD_PRIVMSG = 'PRIVMSG'
    CMD_NOTICE  = 'NOTICE'
    CMD_NICK    = 'NICK'
    CMD_PING    = 'PING'
    CMD_PONG    = 'PONG'
    CMD_TOPIC   = 'TOPIC'
    CMD_ERROR   = 'ERROR'
    CMD_ERRO    = 'ERRO'
    CMD_KILL    = 'KILL'
    ''' Comandos genéricos (não fazem parte de nenhum protocolo IRC) '''
    ALL_MSG     = ':ALL:'
    OUT_MSG     = ':OUT:' 
